"""Live production studio with isolated departments and downloadable artifacts.

The first production implementation intentionally provides deterministic local
outputs that work without paid providers. Provider-backed image, video and 3D
renderers can replace a department adapter without changing the public contract.
"""

from __future__ import annotations

import io
import json
import re
import textwrap
import zipfile
from datetime import UTC, datetime
from typing import Literal

from app.core.auth import UserRecord, current_user
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

router = APIRouter()

Department = Literal[
    "website",
    "code",
    "ui-ux",
    "three-d",
    "video",
    "animation",
    "advertising",
    "documentary",
    "image",
    "branding",
]

DEPARTMENTS: tuple[dict[str, object], ...] = (
    {"id": "website", "name": "Website Studio", "outputs": ["HTML", "CSS", "JavaScript", "ZIP"]},
    {"id": "code", "name": "Code Studio", "outputs": ["source", "tests", "README", "ZIP"]},
    {"id": "ui-ux", "name": "UI/UX Studio", "outputs": ["design system", "wireframe", "prototype brief"]},
    {"id": "three-d", "name": "3D & Three.js Studio", "outputs": ["Three.js scene", "GLTF-ready structure", "ZIP"]},
    {"id": "video", "name": "Video Studio", "outputs": ["script", "shot list", "subtitles", "render plan"]},
    {"id": "animation", "name": "Animation Studio", "outputs": ["storyboard", "timing sheet", "scene plan"]},
    {"id": "advertising", "name": "Advertising Studio", "outputs": ["campaign brief", "ad variants", "CTA plan"]},
    {"id": "documentary", "name": "Documentary Studio", "outputs": ["research outline", "narration", "evidence checklist"]},
    {"id": "image", "name": "Image Studio", "outputs": ["editable SVG", "prompt pack", "export guide"]},
    {"id": "branding", "name": "Branding Studio", "outputs": ["brand strategy", "identity tokens", "usage guide"]},
)


class StudioRequest(BaseModel):
    department: Department
    title: str = Field(min_length=2, max_length=160)
    brief: str = Field(min_length=8, max_length=12_000)
    language: str = Field(default="en-US", max_length=35)
    style: str = Field(default="modern", max_length=80)
    target: str | None = Field(default=None, max_length=160)
    programming_language: str | None = Field(default=None, max_length=40)


def _slug(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip()).strip("-").lower()
    return normalized[:70] or "aionex-project"


def _readme(data: StudioRequest) -> str:
    return textwrap.dedent(
        f"""\
        # {data.title}

        Generated by AIONEX AIOS Production Studio.

        - Department: {data.department}
        - Language: {data.language}
        - Style: {data.style}
        - Target: {data.target or 'General audience'}
        - Generated: {datetime.now(UTC).isoformat()}

        ## Brief

        {data.brief}

        ## Production note

        This downloadable package is a deterministic, editable starting point.
        External AI provider adapters may add photorealistic images, rendered
        video, voice cloning, music, or hosted deployment when configured and
        approved by platform governance.
        """
    )


def _website_files(data: StudioRequest) -> dict[str, str]:
    safe_title = data.title.replace("<", "&lt;").replace(">", "&gt;")
    html = f"""<!doctype html>
<html lang=\"{data.language}\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />
  <title>{safe_title}</title>
  <link rel=\"stylesheet\" href=\"styles.css\" />
</head>
<body>
  <main class=\"hero\">
    <span class=\"eyebrow\">AIONEX AIOS · Website Studio</span>
    <h1>{safe_title}</h1>
    <p>{data.brief}</p>
    <button id=\"action\">Explore project</button>
  </main>
  <script src=\"app.js\"></script>
</body>
</html>
"""
    css = """:root{font-family:Inter,system-ui,sans-serif;color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 20%,#1d4ed8 0,transparent 35%),#050816;color:#fff}.hero{min-height:100vh;display:grid;place-content:center;gap:1.25rem;padding:8vw;max-width:1100px}.eyebrow{letter-spacing:.18em;text-transform:uppercase;opacity:.65}h1{font-size:clamp(3rem,8vw,7rem);line-height:.95;margin:0}p{font-size:clamp(1rem,2vw,1.35rem);line-height:1.7;max-width:760px;opacity:.78}button{width:max-content;border:0;border-radius:999px;padding:1rem 1.5rem;font-weight:700;cursor:pointer}button:hover{transform:translateY(-2px)}\n"""
    js = "document.querySelector('#action')?.addEventListener('click',()=>alert('AIONEX AIOS project is ready for customization.'));\n"
    return {"index.html": html, "styles.css": css, "app.js": js}


def _three_files(data: StudioRequest) -> dict[str, str]:
    html = """<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><style>body{margin:0;overflow:hidden;background:#030712}#label{position:fixed;z-index:2;color:white;font:16px system-ui;padding:20px}</style></head><body><div id=\"label\"></div><script type=\"module\" src=\"scene.js\"></script></body></html>"""
    scene = f"""import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,100);
const renderer=new THREE.WebGLRenderer({{antialias:true}});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(devicePixelRatio);document.body.appendChild(renderer.domElement);
const object=new THREE.Mesh(new THREE.TorusKnotGeometry(1,0.32,160,24),new THREE.MeshStandardMaterial({{color:0x38bdf8,metalness:.65,roughness:.2}}));scene.add(object);
scene.add(new THREE.HemisphereLight(0xffffff,0x111827,2.4));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(3,4,5);scene.add(key);camera.position.z=4;
document.querySelector('#label').textContent={json.dumps(data.title)};
function frame(){{object.rotation.x+=.004;object.rotation.y+=.008;renderer.render(scene,camera);requestAnimationFrame(frame)}}frame();
addEventListener('resize',()=>{{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}});
"""
    return {"index.html": html, "scene.js": scene, "assets/README.md": "Place GLB/GLTF, textures and HDR environments in this directory.\n"}


def _video_files(data: StudioRequest) -> dict[str, str]:
    shots = [
        {"shot": 1, "duration_seconds": 4, "visual": "Opening establishing shot", "audio": "Music rise"},
        {"shot": 2, "duration_seconds": 7, "visual": data.brief[:240], "audio": "Primary narration"},
        {"shot": 3, "duration_seconds": 6, "visual": "Detail and proof sequence", "audio": "Narration with natural sound"},
        {"shot": 4, "duration_seconds": 5, "visual": "Resolution and call to action", "audio": "Music resolve"},
    ]
    srt = """1
00:00:00,000 --> 00:00:04,000
A new story begins.

2
00:00:04,000 --> 00:00:11,000
The central idea is introduced with clarity and purpose.

3
00:00:11,000 --> 00:00:17,000
Evidence, detail and human context build trust.

4
00:00:17,000 --> 00:00:22,000
The story closes with a memorable next step.
"""
    render = """#!/usr/bin/env bash
set -euo pipefail
# Replace shot-*.mp4 with generated or filmed scene assets.
ffmpeg -f concat -safe 0 -i inputs.txt -vf subtitles=subtitles.srt -c:v libx264 -c:a aac -movflags +faststart final.mp4
"""
    inputs = "file 'shot-01.mp4'\nfile 'shot-02.mp4'\nfile 'shot-03.mp4'\nfile 'shot-04.mp4'\n"
    return {
        "production/shot-list.json": json.dumps(shots, ensure_ascii=False, indent=2),
        "production/subtitles.srt": srt,
        "production/render.sh": render,
        "production/inputs.txt": inputs,
        "production/provider-prompts.md": f"# Provider prompts\n\nStyle: {data.style}\n\nAudience: {data.target or 'general'}\n\nBrief: {data.brief}\n",
    }


def _image_files(data: StudioRequest) -> dict[str, str]:
    title = data.title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    svg = f"""<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1600\" height=\"900\" viewBox=\"0 0 1600 900\"><defs><linearGradient id=\"g\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop stop-color=\"#020617\"/><stop offset=\"1\" stop-color=\"#1d4ed8\"/></linearGradient></defs><rect width=\"1600\" height=\"900\" fill=\"url(#g)\"/><circle cx=\"1250\" cy=\"180\" r=\"280\" fill=\"#38bdf8\" opacity=\".22\"/><text x=\"110\" y=\"400\" fill=\"white\" font-family=\"Arial,sans-serif\" font-size=\"92\" font-weight=\"700\">{title}</text><text x=\"115\" y=\"485\" fill=\"white\" opacity=\".72\" font-family=\"Arial,sans-serif\" font-size=\"34\">Editable AIONEX AIOS visual</text></svg>"""
    return {"visual.svg": svg, "prompt-pack.md": f"# Image prompt pack\n\n{data.brief}\n\nStyle: {data.style}\nLanguage: {data.language}\n"}


def _strategy_files(data: StudioRequest) -> dict[str, str]:
    sections = {
        "ui-ux": ["User problem", "Personas", "Information architecture", "Wireframes", "Design tokens", "Accessibility", "Usability tests"],
        "animation": ["Concept", "Characters", "Storyboard", "Timing", "Key poses", "Transitions", "Sound design"],
        "advertising": ["Product truth", "Audience", "Campaign promise", "Hooks", "Formats", "Calls to action", "Measurement"],
        "documentary": ["Central question", "Research sources", "Interview plan", "Narrative arc", "Fact checking", "Rights and releases", "Distribution"],
        "branding": ["Purpose", "Positioning", "Audience", "Voice", "Visual system", "Logo usage", "Launch plan"],
    }[data.department]
    content = [f"# {data.title}", "", f"Brief: {data.brief}", "", f"Style: {data.style}", ""]
    for index, section in enumerate(sections, start=1):
        content.extend([f"## {index}. {section}", "", "- Decision:", "- Evidence:", "- Deliverable:", ""])
    return {"production-plan.md": "\n".join(content)}


def _code_files(data: StudioRequest) -> dict[str, str]:
    language = (data.programming_language or "python").lower()
    if language in {"javascript", "typescript"}:
        extension = "ts" if language == "typescript" else "js"
        code = f"export function projectSummary() {{ return {json.dumps(data.brief)}; }}\nconsole.log(projectSummary());\n"
        test = "import { projectSummary } from './src/index';\nif (!projectSummary()) throw new Error('summary missing');\n"
        return {f"src/index.{extension}": code, f"tests/basic.{extension}": test, "package.json": json.dumps({"name": _slug(data.title), "version": "1.0.0", "private": True, "scripts": {"test": f"node tests/basic.{extension}"}}, indent=2)}
    code = f'''"""{data.title}."""\n\ndef project_summary() -> str:\n    return {data.brief!r}\n\nif __name__ == "__main__":\n    print(project_summary())\n'''
    test = "from src.main import project_summary\n\ndef test_project_summary():\n    assert project_summary().strip()\n"
    return {"src/main.py": code, "tests/test_main.py": test, "requirements.txt": "pytest==8.3.5\n"}


def _department_files(data: StudioRequest) -> dict[str, str]:
    if data.department == "website":
        return _website_files(data)
    if data.department == "code":
        return _code_files(data)
    if data.department == "three-d":
        return _three_files(data)
    if data.department in {"video"}:
        return _video_files(data)
    if data.department == "image":
        return _image_files(data)
    return _strategy_files(data)


@router.get("/departments")
async def departments() -> dict[str, object]:
    return {"departments": DEPARTMENTS, "count": len(DEPARTMENTS)}


@router.post("/generate")
async def generate_artifact(
    data: StudioRequest,
    actor: UserRecord = Depends(current_user),
) -> StreamingResponse:
    if not data.brief.strip():
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="Brief is required")

    files = {"README.md": _readme(data), **_department_files(data)}
    manifest = {
        "schema": "aionex.production-artifact.v1",
        "department": data.department,
        "title": data.title,
        "language": data.language,
        "style": data.style,
        "created_by": actor.id,
        "created_at": datetime.now(UTC).isoformat(),
        "files": sorted(files),
    }
    files["aionex-manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=2)

    archive = io.BytesIO()
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for path, content in files.items():
            bundle.writestr(path, content)
    archive.seek(0)
    filename = f"{_slug(data.title)}-{data.department}.zip"
    return StreamingResponse(
        archive,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-AIONEX-Department": data.department,
            "Cache-Control": "no-store",
        },
    )
